"""Automated tests for testing dynamic skill_save and skill_delete tools on AION Skills Hub."""

from __future__ import annotations

import os

# Abilita esplicitamente la scrittura per i test
os.environ["AION_SKILL_WRITE_ENABLED"] = "1"

from pathlib import Path
import pytest

from src.skill_registry import skill_registry
from mcp_servers.skills_hub.server import skill_save, skill_delete


def test_skills_hub_save_and_delete_flow():
    # Make sure registry is clean/loaded
    skill_registry.reload()

    test_name = "test-automated-saving-flow"
    test_desc = "Testing dynamic saving of skills on Skills Hub"
    test_content = (
        "# Test Automated Skill\nThis is a temporary skill generated by test suite."
    )
    test_tags = ["test", "automated"]

    # 1. Save curated skill
    res = skill_save(
        name=test_name,
        description=test_desc,
        content=test_content,
        tags=test_tags,
        category="curated",
    )

    assert "saved successfully" in res
    assert test_name in res

    # 2. Verify files exist in both locations
    path_curated = skill_registry.curated_dir / f"{test_name}.md"
    path_fallback = skill_registry.curated_fallback_dir / f"{test_name}.md"

    assert path_curated.exists(), f"File should be written to {path_curated}"
    assert path_fallback.exists(), f"File should be written to {path_fallback}"

    # 3. Verify SkillRegistry has loaded it and metadata matches
    skill_registry.reload()
    meta = skill_registry.get_meta(test_name)
    assert meta is not None, "SkillRegistry should load the saved skill"
    assert meta["name"] == test_name
    assert meta["description"] == test_desc
    assert meta["tags"] == test_tags
    assert meta["source"] == "curated"

    body = skill_registry.get_skill_full(test_name)
    assert body is not None
    assert "This is a temporary skill" in body

    # 4. Save generated skill
    test_gen_name = "test-generated-automated"
    res_gen = skill_save(
        name=test_gen_name,
        description=test_desc,
        content=test_content,
        tags=test_tags,
        category="generated",
    )
    assert "saved successfully" in res_gen
    path_gen = skill_registry.generated_dir / f"{test_gen_name}.md"
    assert path_gen.exists()

    skill_registry.reload()
    assert skill_registry.get_meta(test_gen_name) is not None

    # 5. Delete generated skill
    res_del_gen = skill_delete(test_gen_name)
    assert "deleted successfully" in res_del_gen
    assert not path_gen.exists()

    # 6. Delete curated skill
    res_del = skill_delete(test_name)
    assert "deleted successfully" in res_del
    assert test_name in res_del

    # 7. Verify files are unlinked
    assert not path_curated.exists(), "File should be deleted"
    assert not path_fallback.exists(), "File should be deleted"

    # 8. Verify registry no longer lists it
    skill_registry.reload()
    assert skill_registry.get_meta(test_name) is None
    assert skill_registry.get_meta(test_gen_name) is None


def test_skills_hub_gating_disabled(monkeypatch):
    # Set gating to disabled
    monkeypatch.setenv("AION_SKILL_WRITE_ENABLED", "0")

    # Verify save fails with gating error
    res_save = skill_save(
        name="test-gated-skill",
        description="test",
        content="test",
    )
    assert "Error: skill write/delete" in res_save

    # Verify delete fails with gating error
    res_delete = skill_delete("test-gated-skill")
    assert "Error: skill write/delete" in res_delete
