packages:
  - 'admin-ui'
  - 'chat-ui'
  - 'website'
  - 'services/pi-long-run'
allowBuilds:
  '@google/genai': false
  '@swc/core': true
  core-js: true
  esbuild: false
  protobufjs: false
  sharp: true
  unrs-resolver: true
