packages:
  - 'admin-ui'
  - 'chat-ui'
  - 'website'
  - 'services/pi-long-run'
allowBuilds:
  '@google/genai': set this to true or false
  '@swc/core': true
  core-js: true
  esbuild: set this to true or false
  protobufjs: set this to true or false
  sharp: true
  unrs-resolver: true
