"""Initial baseline

Revision ID: 15a42b5aff9f
Revises: 
Create Date: 2026-04-28 23:14:25.778847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a42b5aff9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'trace_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index('idx_audit_log_trace', table_name='audit_log')
    op.create_index(op.f('ix_audit_log_trace_id'), 'audit_log', ['trace_id'], unique=False)
    op.alter_column('eval_results', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('eval_results', 'run_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('eval_results', 'case_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('eval_results', 'score',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('eval_results', 'latency_sec',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('eval_results', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('eval_runs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('eval_runs', 'dataset_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('eval_runs', 'profile_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('eval_runs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('eval_runs', 'overall_score',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('eval_runs', 'metadata',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'feedbacks', 'messages', ['message_id'], ['id'])
    op.alter_column('messages', 'trace_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index('idx_messages_trace', table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=True)
    op.create_index(op.f('ix_messages_trace_id'), 'messages', ['trace_id'], unique=False)
    op.create_unique_constraint('uq_msg_conv_seq', 'messages', ['conversation_id', 'seq'])
    op.alter_column('steps', 'trace_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_steps_trace_id'), 'steps', ['trace_id'], unique=False)
    op.create_unique_constraint('uq_users_tenant_identifier', 'users', ['tenant_id', 'identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_tenant_identifier', 'users', type_='unique')
    op.drop_index(op.f('ix_steps_trace_id'), table_name='steps')
    op.alter_column('steps', 'trace_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_msg_conv_seq', 'messages', type_='unique')
    op.drop_index(op.f('ix_messages_trace_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index('idx_messages_trace', 'messages', ['trace_id'], unique=False)
    op.alter_column('messages', 'trace_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'feedbacks', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.alter_column('eval_runs', 'metadata',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('eval_runs', 'overall_score',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('eval_runs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('eval_runs', 'profile_name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('eval_runs', 'dataset_name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('eval_runs', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('eval_results', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('eval_results', 'latency_sec',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('eval_results', 'score',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('eval_results', 'case_id',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('eval_results', 'run_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('eval_results', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_audit_log_trace_id'), table_name='audit_log')
    op.create_index('idx_audit_log_trace', 'audit_log', ['trace_id'], unique=False)
    op.alter_column('audit_log', 'trace_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
