"use client";

import { ShieldCheck, ShieldAlert, FileCode, CheckCircle2, XCircle, Search, Save, Trash2, X, AlertTriangle, Download, ChevronRight, FileSearch, Shield, Cpu, Activity } from "lucide-react";
import { apiFetch } from "@/lib/api/headers"
import { useState, useEffect, useRef } from "react";
import { apiBase } from "@/lib/api";
import { getStoredToken } from "@/lib/auth/storage";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { PageToast, ToastState } from "@/components/PageToast";

export default function SecurityAudit() {
  const [targetPath, setTargetPath] = useState("");
  const [scanResult, setScanResult] = useState<any>(null);
  const [scanning, setScanning] = useState(false);
  const [toast, setToast] = useState<ToastState>(null);

  const [investigating, setInvestigating] = useState(false);
  const [investigationReport, setInvestigationReport] = useState("");
  const [investigationData, setInvestigationData] = useState<any>(null);
  const [investigatingFile, setInvestigatingFile] = useState<string | null>(null);
  const [selectedAgent, setSelectedAgent] = useState("Security Officer");
  const [availableProfiles, setAvailableProfiles] = useState<any[]>([]);
  const [savedReports, setSavedReports] = useState<any[]>([]);
  const [scanHistory, setScanHistory] = useState<any[]>([]);

  useEffect(() => {
    apiFetch(`${apiBase()}/admin/profiles`)
      .then(res => res.json())
      .then(data => setAvailableProfiles(data))
      .catch(err => console.error("Failed to fetch profiles", err));

    fetchReports();
    fetchScanHistory();
  }, []);

  const fetchScanHistory = async () => {
    try {
      const res = await apiFetch(`${apiBase()}/admin/security/scans`);
      const data = await res.json();
      setScanHistory(data.scans || []);
    } catch (err) {
      console.error("Failed to fetch scan history", err);
    }
  };

  const fetchReports = async () => {
    try {
      const res = await apiFetch(`${apiBase()}/admin/security/reports`);
      const data = await res.json();
      setSavedReports(data.reports || []);
    } catch (err) {
      console.error("Failed to fetch reports", err);
    }
  };

  const runScan = async () => {
    setScanning(true);
    try {
      const res = await apiFetch(`${apiBase()}/admin/mcp/scan`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ path: targetPath || "mcp_servers" })
      });
      if (!res.ok) throw new Error("Failed to execute scan");
      const data = await res.json();
      setScanResult(data);
      setToast({ message: "Scan completed successfully", variant: "success" });
      fetchScanHistory();
    } catch (e: any) {
      console.error(e);
      setToast({ message: "Scan failed: " + e.message, variant: "error" });
    } finally {
      setScanning(false);
    }
  };

  const exportToMarkdown = () => {
    if (!investigatingFile) return;

    const fileName = investigatingFile.split("/").pop();
    const date = new Date().toLocaleString();

    let content = `# 🛡️ AION SECURITY AUDIT REPORT\n\n`;
    content += `**File**: \`${investigatingFile}\`  \n`;
    content += `**Date**: ${date}  \n`;
    content += `**Investigator**: ${selectedAgent}  \n\n`;
    content += `---\n\n`;

    if (investigationData) {
      content += `## 📊 EXECUTIVE SUMMARY\n\n`;
      content += `> **VERDICT**: ${investigationData.verdict || "UNKNOWN"}\n`;
      content += `> **RISK SCORE**: ${investigationData.risk_score || "N/A"}%\n\n`;
      content += `${investigationData.summary || ""}\n\n`;

      if (investigationData.fixes && investigationData.fixes.length > 0) {
        content += `### 🛠️ RECOMMENDED MITIGATIONS\n`;
        investigationData.fixes.forEach((fix: string) => {
          content += `- [ ] ${fix}\n`;
        });
        content += `\n`;
      }
      content += `---\n\n`;
    }

    content += `## 🔍 TECHNICAL ANALYSIS\n\n`;
    // Clean text from JSON blocks before saving
    const cleanBody = investigationReport.replace(/```json\s*([\s\S]*?)\s*```/g, "").replace(/\{[\s\S]*?\}/g, (match) => {
      try { JSON.parse(match); return ""; } catch (e) { return match; }
    });
    content += cleanBody;
    content += `\n\n---\n*Generated by AION Security Intelligence Officer*`;

    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `AION_Security_Report_${fileName}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const loadSavedReport = async (reportId: string) => {
    setInvestigating(true);
    try {
      const res = await apiFetch(`${apiBase()}/admin/security/report/${reportId}`);
      const data = await res.json();
      setInvestigatingFile(data.path);
      setInvestigationReport(data.content);

      // Attempt to extract metadata if content has been saved with it
      const jsonMatch = data.content.match(/```json\s*([\s\S]*?)\s*```/);
      if (jsonMatch) {
        try {
          setInvestigationData(JSON.parse(jsonMatch[1]));
        } catch (e) { }
      }
    } catch (e) {
      console.error("Failed to load report", e);
    } finally {
      setInvestigating(false);
    }
  };

  const loadScanResult = async (scanId: string) => {
    try {
      const res = await apiFetch(`${apiBase()}/admin/security/scans/${scanId}`);
      const data = await res.json();
      setScanResult(data);
      setToast({ message: `Loaded scan from ${new Date(data.timestamp).toLocaleString()}`, variant: "success" });
    } catch (e) {
      console.error("Failed to load scan", e);
    }
  };

  const handleInvestigate = async (file: string) => {
    setInvestigating(true);
    setInvestigatingFile(file);
    setInvestigationReport("");
    setInvestigationData(null);

    const token = getStoredToken();

    try {
      const eventSource = new EventSource(`${apiBase()}/admin/security/investigate?path=${encodeURIComponent(file)}&profile=${encodeURIComponent(selectedAgent)}&access_token=${token}`);

      let fullText = "";
      eventSource.onmessage = (event) => {
        const data = JSON.parse(event.data);
        if (data.type === "token") {
          fullText += data.content;
          setInvestigationReport(fullText);
        } else if (data.type === "final") {
          console.log("--- ANALYSIS COMPLETE ---");
          fetchReports(); // Refresh history

          // --- ULTRA ROBUST JSON EXTRACTION ---
          let jsonStr = "";
          const markdownMatch = fullText.match(/```json\s*([\s\S]*?)\s*```/);

          if (markdownMatch && markdownMatch[1]) {
            jsonStr = markdownMatch[1].trim();
          } else {
            // Find the outermost JSON object at the end of the text
            const lastOpenBrace = fullText.lastIndexOf("{");
            const lastCloseBrace = fullText.lastIndexOf("}");
            if (lastOpenBrace !== -1 && lastCloseBrace !== -1 && lastOpenBrace < lastCloseBrace) {
              jsonStr = fullText.substring(lastOpenBrace, lastCloseBrace + 1);
            }
          }

          if (jsonStr) {
            try {
              // Deep clean: remove control chars and common AI hallucinations
              let cleaned = jsonStr.replace(/[\u0000-\u001F\u007F-\u009F]/g, "").trim();

              // --- FIX COMMON AI HALLUCINATIONS (Python-isms in JSON) ---
              // 1. Handle unquoted 'datetime.something' or just 'datetime'
              cleaned = cleaned.replace(/datetime\.[\w()]*/g, (m) => `"${m}"`);
              // 2. Handle 'None' (Python) instead of 'null' (JSON)
              cleaned = cleaned.replace(/:\s*None/g, ": null");
              // 3. Handle 'True/False' (Python) instead of 'true/false' (JSON)
              cleaned = cleaned.replace(/:\s*True/g, ": true").replace(/:\s*False/g, ": false");

              // Basic auto-fix for missing closing brace
              if (cleaned.startsWith("{") && !cleaned.endsWith("}")) cleaned += "}";

              const parsed = JSON.parse(cleaned);
              setInvestigationData(parsed);
            } catch (e) {
              console.error("❌ JSON parsing failed:", e);
            }
          }

          eventSource.close();
          setInvestigating(false);
          setInvestigationReport(fullText);
        }
      };

      eventSource.onerror = (error) => {
        //Triggered here!!!
        console.log(error)

        eventSource.close();
        setInvestigating(false);
      };

    } catch (e) {
      console.error(e);
      setInvestigating(false);
    }
  };

  const handleMarkSafe = async (file: string) => {
    if (!scanResult?.id) return;

    try {
      const res = await apiFetch(`${apiBase()}/admin/security/scans/${scanResult.id}/trust`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ path: file })
      });
      if (res.ok) {
        setToast({ message: `File ${file.split('/').pop()} marked as trusted for this scan`, variant: "success" });
        // Update local state instead of triggering a new persistent scan record
        setScanResult((prev: any) => {
          if (!prev) return prev;
          const newViolations = { ...prev.violations };
          if (newViolations[file]) {
            newViolations[file] = { ...newViolations[file], is_trusted: true };
          }
          // Recalculate is_safe: it's safe if all violations are either trusted or low/medium severity
          const isSafe = Object.values(newViolations).every((v: any) =>
            v.is_trusted || !v.list.some((violation: any) => violation.severity === 'high' || violation.severity === 'critical')
          );
          return { ...prev, violations: newViolations, is_safe: isSafe };
        });

        // Refresh history to show updated safety status
        fetchScanHistory();
      } else {
        throw new Error("Failed to update trust status");
      }
    } catch (e: any) {
      console.error("Failed to mark file as safe", e);
      setToast({ message: e.message, variant: "error" });
    }
  };

  return (
    <div className="space-y-8 pb-32">
      {/* Header */}
      <header className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 p-6">
        <div className="space-y-1">
          <h2 className="text-3xl font-extrabold tracking-tight text-white">Security Audit</h2>
          <p className="text-md text-gray-400 max-w-2xl mt-2">
            Monitor and scan MCP servers for vulnerabilities using AION Antivirus and specialized AI Security Agents.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <div className="px-4 py-2 bg-green-500/10 border border-green-500/20 rounded-xl flex items-center gap-2">
            <Activity className="w-4 h-4 text-green-400" />
            <span className="text-xs font-bold text-green-400 uppercase tracking-wider">System Protected</span>
          </div>
        </div>
      </header>

      {/* Scanner Card */}
      <div className="glass-card p-6 sm:p-8 bg-gradient-to-b from-blue-600/10 to-transparent border border-blue-500/20 rounded-3xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/5 rounded-full blur-3xl pointer-events-none" />

        <div className="flex flex-col lg:flex-row lg:items-center gap-8">
          <div className="flex items-center gap-6">
            <div className="w-20 h-20 rounded-2xl bg-gradient-to-tr from-blue-600 to-indigo-600 flex items-center justify-center text-white shadow-xl shadow-blue-600/30">
              <ShieldCheck className="w-10 h-10" />
            </div>
            <div className="flex-1">
              <h3 className="text-2xl font-bold text-white tracking-tight">AION Security Intelligence</h3>
              <div className="flex items-center gap-3 mt-2">
                <span className="text-xs font-bold text-gray-500 uppercase tracking-widest">Active Investigator:</span>
                <div className="relative">
                  <select
                    value={selectedAgent}
                    onChange={(e) => setSelectedAgent(e.target.value)}
                    className="bg-black/40 text-blue-400 text-[11px] font-bold uppercase border border-white/10 rounded-lg px-3 py-1.5 outline-none cursor-pointer hover:border-blue-500/40 transition-all appearance-none pr-8"
                  >
                    {availableProfiles.map(p => (
                      <option key={p.name} value={p.name} className="bg-[#1a1a1a] text-gray-300">
                        {p.name}
                      </option>
                    ))}
                  </select>
                  <ChevronRight className="w-3 h-3 text-blue-400 absolute right-2.5 top-1/2 -translate-y-1/2 rotate-90 pointer-events-none" />
                </div>
              </div>
            </div>
          </div>

          <div className="flex-1 flex flex-col sm:flex-row gap-4 items-end sm:items-center">
            <div className="relative flex-1 w-full group">
              <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 group-focus-within:text-blue-400 transition-colors" />
              <input
                value={targetPath}
                onChange={(e) => setTargetPath(e.target.value)}
                placeholder="Scan Path (e.g. mcp_servers)"
                className="w-full bg-black/40 backdrop-blur-sm border border-white/10 rounded-xl pl-10 pr-4 py-3.5 text-sm text-white placeholder:text-gray-600 focus:border-blue-500/80 focus:ring-4 focus:ring-blue-500/10 outline-none transition-all shadow-inner font-medium"
              />
            </div>
            <button
              onClick={runScan}
              disabled={scanning}
              className="w-full sm:w-auto px-8 py-3.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white rounded-xl font-bold text-sm transition-all shadow-lg shadow-blue-600/20 disabled:opacity-50 flex items-center justify-center gap-2 whitespace-nowrap active:scale-95"
            >
              {scanning ? (
                <>
                  <Activity className="w-4 h-4 animate-pulse" />
                  ANALYZING SYSTEM...
                </>
              ) : (
                <>
                  <Shield className="w-4 h-4" />
                  RUN FULL SYSTEM SCAN
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Analysis Results & History */}
        <div className="lg:col-span-5 xl:col-span-4 space-y-8">
          <div className="space-y-4">
            <div className="flex items-center justify-between px-1">
              <h3 className="text-xs font-bold uppercase tracking-wider text-gray-400">Static Analysis Results</h3>
            </div>

            <div className="glass-card h-[700px] flex flex-col border border-white/10 rounded-2xl bg-[#121212]/50 overflow-hidden">
              {!scanResult ? (
                <div className="flex-1 flex flex-col items-center justify-center p-8 text-center space-y-4">
                  <div className="p-4 bg-white/5 rounded-full">
                    <FileCode className="w-10 h-10 text-gray-600" />
                  </div>
                  <p className="text-sm text-gray-500 font-medium max-w-[180px]">Perform a scan to check system integrity</p>
                </div>
              ) : (
                <div className="flex-1 overflow-y-auto custom-scrollbar divide-y divide-white/5">
                  {scanResult.is_safe ? (
                    <div className="p-12 flex flex-col items-center justify-center text-center space-y-4">
                      <div className="w-16 h-16 rounded-full bg-green-500/10 flex items-center justify-center border border-green-500/20">
                        <CheckCircle2 className="w-8 h-8 text-green-500 animate-in zoom-in duration-500" />
                      </div>
                      <div className="space-y-1">
                        <h3 className="text-lg font-bold text-white">Core Intact</h3>
                        <p className="text-xs text-gray-500 max-w-xs">AION Antivirus verified all endpoints. No unauthorized patterns detected.</p>
                      </div>
                    </div>
                  ) : (
                    Object.entries(scanResult.violations || {}).map(([file, data]: [string, any]) => {
                      const list = data.list || [];
                      const isTrusted = data.is_trusted || false;

                      return (
                        <div key={file} className={`p-5 space-y-4 transition-colors group ${isTrusted ? 'bg-green-500/[0.02] hover:bg-green-500/[0.04]' : 'bg-red-500/[0.02] hover:bg-red-500/[0.04]'}`}>
                          <div className="flex items-center justify-between gap-2">
                            <div className="flex items-center gap-2 min-w-0">
                              {isTrusted ? (
                                <ShieldCheck className="w-4 h-4 text-green-500 shrink-0" />
                              ) : (
                                <ShieldAlert className="w-4 h-4 text-red-500 shrink-0" />
                              )}
                              <div className="text-xs font-mono font-bold text-gray-300 truncate">{file.split('/').pop()}</div>
                              {isTrusted && <span className="text-[8px] px-1.5 py-0.5 bg-green-500/20 text-green-400 border border-green-500/30 rounded font-black uppercase tracking-tighter">Trusted</span>}
                            </div>
                            {(() => {
                              const highest = list.reduce((prev: string, curr: any) => {
                                const weights: any = { low: 1, medium: 2, high: 3, critical: 4 };
                                return (weights[curr.severity] > weights[prev]) ? curr.severity : prev;
                              }, "low");
                              const colors: any = {
                                low: "bg-blue-500/10 text-blue-400 border-blue-500/20",
                                medium: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20",
                                high: "bg-orange-500/10 text-orange-400 border-orange-500/20",
                                critical: "bg-red-500/10 text-red-400 border-red-500/20 animate-pulse font-black"
                              };
                              return <span className={`text-[9px] px-2 py-0.5 rounded-md border uppercase font-bold tracking-tight ${colors[highest]}`}>{highest}</span>
                            })()}
                          </div>

                          <div className="space-y-1.5 pl-6">
                            {list.slice(0, 3).map((v: any, idx: number) => (
                              <div key={idx} className="text-[11px] text-gray-500 flex items-start gap-2">
                                <span className={`w-1 h-1 rounded-full mt-1.5 shrink-0 ${isTrusted ? 'bg-green-900' : 'bg-gray-700'}`} />
                                <span className={isTrusted ? 'opacity-50' : ''}>{v.message}</span>
                              </div>
                            ))}
                            {list.length > 3 && <p className="text-[10px] text-gray-600 italic">...and {list.length - 3} more</p>}
                          </div>

                          <div className="flex items-center gap-2 pt-2">
                            <button
                              onClick={() => handleInvestigate(file)}
                              className="flex-1 flex items-center justify-center gap-2 py-2 bg-blue-600/10 hover:bg-blue-600 text-blue-400 hover:text-white text-[10px] rounded-lg font-bold border border-blue-600/20 transition-all"
                            >
                              <FileSearch className="w-3.5 h-3.5" /> INVESTIGATE
                            </button>
                            {!isTrusted && (
                              <button
                                onClick={() => handleMarkSafe(file)}
                                className="px-3 py-2 bg-white/5 hover:bg-green-500/10 border border-white/5 hover:border-green-500/20 text-gray-500 hover:text-green-400 text-[10px] rounded-lg font-bold transition-all"
                              >
                                TRUST
                              </button>
                            )}
                          </div>
                        </div>
                      );
                    })
                  )}
                </div>
              )}
            </div>
          </div>

          {/* Audit History */}
          <div className="space-y-4 pt-4">
            <div className="flex items-center justify-between px-1">
              <h3 className="text-xs font-bold uppercase tracking-wider text-gray-400">Scan & Audit History</h3>
            </div>

            {/* Tabs for History */}
            <div className="glass-card min-h-[300px] flex flex-col border border-white/10 rounded-2xl bg-[#121212]/50 overflow-hidden">
              <div className="flex border-b border-white/5 bg-white/[0.02]">
                <button className="flex-1 py-3 text-[10px] font-bold uppercase tracking-widest text-blue-400 border-b-2 border-blue-500 bg-blue-500/5">System Scans</button>
                <button className="flex-1 py-3 text-[10px] font-bold uppercase tracking-widest text-gray-500 hover:text-gray-300 transition-colors">AI Reports</button>
              </div>

              <div className="flex-1 overflow-y-auto max-h-[400px] divide-y divide-white/5 custom-scrollbar">
                {scanHistory.length === 0 ? (
                  <div className="flex-1 flex flex-col items-center justify-center p-8 text-gray-600">
                    <p className="text-xs italic">No past scans found.</p>
                  </div>
                ) : (
                  scanHistory.map((scan) => (
                    <div
                      key={scan.id}
                      onClick={() => loadScanResult(scan.id)}
                      className="p-4 flex items-center gap-4 hover:bg-white/5 cursor-pointer transition-all group"
                    >
                      <div className={`w-10 h-10 rounded-xl flex items-center justify-center transition-all border ${scan.is_safe ? 'bg-green-500/10 text-green-500 border-green-500/20' : 'bg-red-500/10 text-red-500 border-red-500/20'}`}>
                        <ShieldCheck className="w-5 h-5" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="text-sm font-bold text-gray-300 truncate group-hover:text-white transition-colors">{scan.target_path}</div>
                        <div className="text-[10px] text-gray-500 mt-0.5">{new Date(scan.timestamp).toLocaleString()}</div>
                      </div>
                      <div className="flex flex-col items-end gap-1">
                        <span className={`text-[8px] px-1.5 py-0.5 rounded border uppercase font-black ${scan.is_safe ? 'bg-green-500/10 text-green-400 border-green-500/20' : 'bg-red-500/10 text-red-400 border-red-500/20'}`}>
                          {scan.is_safe ? "CLEAN" : "THREATS"}
                        </span>
                        <ChevronRight className="w-3 h-3 text-gray-600 group-hover:text-blue-400 transition-all" />
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>

        </div>

        {/* Right Column: AI Investigation Report */}
        <div className="lg:col-span-7 xl:col-span-8 flex flex-col space-y-4">
          <div className="flex items-center justify-between px-1">
            <h3 className="text-xs font-bold uppercase tracking-wider text-gray-400">AI Intelligence Report</h3>
          </div>
          <div className={`glass-card flex-1 h-[700px] flex flex-col border border-white/10 rounded-3xl bg-gradient-to-b from-[#181818]/90 to-[#121212]/90 shadow-2xl relative overflow-hidden transition-all duration-500 ${investigating ? 'ring-2 ring-blue-500/50' : ''}`}>
            <div className="absolute top-0 right-0 w-96 h-96 bg-blue-500/[0.03] rounded-full blur-3xl pointer-events-none" />

            {investigatingFile ? (
              <div className="flex flex-col h-full relative z-10">
                {/* Report Header */}
                <div className="p-6 border-b border-white/10 bg-white/5 backdrop-blur-md flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-blue-600 to-indigo-600 flex items-center justify-center shadow-lg shadow-blue-600/20">
                      <ShieldCheck className="w-7 h-7 text-white" />
                    </div>
                    <div>
                      <h4 className="text-lg font-bold text-white flex items-center gap-2">
                        {investigatingFile.split('/').pop()}
                      </h4>
                      <div className="flex items-center gap-2 mt-0.5">
                        <div className={`w-2 h-2 rounded-full ${investigating ? 'bg-blue-500 animate-pulse' : 'bg-green-500'}`} />
                        <span className="text-[10px] uppercase font-bold tracking-widest text-gray-400">
                          {investigating ? "Analyzing Tokens..." : "Investigation Complete"}
                        </span>
                      </div>
                    </div>
                  </div>
                  {!investigating && (
                    <button
                      onClick={exportToMarkdown}
                      className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 text-gray-300 hover:text-white text-xs font-bold rounded-xl border border-white/10 transition-all"
                    >
                      <Download className="w-4 h-4" /> EXPORT REPORT
                    </button>
                  )}
                </div>

                <div className="flex-1 flex flex-col p-6 sm:p-8 overflow-hidden">
                  {/* Summary Badges */}
                  {(!investigating && investigationReport) && (
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8 animate-in fade-in slide-in-from-top-4 duration-500">
                      <div className={`p-5 rounded-2xl border flex flex-col gap-1 ${!investigationData ? 'bg-white/5 border-white/10' :
                        investigationData.verdict === 'SICURO' ? 'bg-green-500/10 border-green-500/20' :
                          investigationData.verdict === 'SOSPETTO' ? 'bg-yellow-500/10 border-yellow-500/20' : 'bg-red-500/10 border-red-500/20'
                        }`}>
                        <span className="text-[10px] uppercase font-bold opacity-50 tracking-wider">AI Security Verdict</span>
                        <span className={`text-2xl font-black tracking-tight ${!investigationData ? 'text-gray-400' :
                          investigationData.verdict === 'SICURO' ? 'text-green-400' :
                            investigationData.verdict === 'SOSPETTO' ? 'text-yellow-400' : 'text-red-400'
                          }`}>{investigationData?.verdict || "MANUAL REVIEW REQUIRED"}</span>
                      </div>
                      <div className="p-5 rounded-2xl bg-white/5 border border-white/10 flex flex-col gap-1">
                        <span className="text-[10px] uppercase font-bold opacity-50 tracking-wider">Threat Risk Score</span>
                        <span className="text-2xl font-black tracking-tight text-white">{investigationData?.risk_score !== undefined ? `${investigationData.risk_score}%` : "—"}</span>
                      </div>
                    </div>
                  )}

                  {/* Markdown Content */}
                  <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar space-y-6">
                    <div className="prose prose-invert max-w-none prose-sm prose-p:leading-relaxed prose-pre:bg-black/40 prose-pre:border prose-pre:border-white/10 prose-pre:rounded-2xl prose-table:border prose-table:border-white/10 prose-th:bg-white/5 prose-th:p-3 prose-td:p-3 prose-td:border-b prose-td:border-white/5">
                      <ReactMarkdown remarkPlugins={[remarkGfm]}>
                        {investigationReport.replace(/```json\s*([\s\S]*?)\s*```/g, "").replace(/\{[\s\S]*?\}/g, (match) => {
                          try { JSON.parse(match); return ""; } catch (e) { return match; }
                        }) || (investigating ? "Initializing secure analysis protocol..." : "")}
                      </ReactMarkdown>
                    </div>

                    {/* Recommended Actions */}
                    {investigationData?.fixes && investigationData.fixes.length > 0 && (
                      <div className="pt-8 border-t border-white/5 animate-in fade-in duration-700">
                        <div className="flex items-center gap-2 mb-4">
                          <Activity className="w-4 h-4 text-blue-400" />
                          <h5 className="text-[11px] uppercase font-bold text-blue-400 tracking-widest">Recommended Mitigations</h5>
                        </div>
                        <div className="space-y-3">
                          {investigationData.fixes.map((fix: string, i: number) => (
                            <div key={i} className="flex items-center gap-4 p-4 bg-white/[0.03] border border-white/5 rounded-2xl hover:bg-white/[0.05] hover:border-white/10 transition-all group">
                              <div className="w-8 h-8 rounded-full bg-blue-500/10 flex items-center justify-center shrink-0 border border-blue-500/20 group-hover:bg-blue-500/20 transition-all">
                                <CheckCircle2 className="w-4 h-4 text-blue-400" />
                              </div>
                              <span className="text-sm text-gray-300 font-medium">{fix}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center p-12 text-center space-y-6">
                <div className="w-20 h-20 rounded-3xl bg-white/5 border border-white/5 flex items-center justify-center text-gray-600">
                  <ShieldAlert className="w-10 h-10 opacity-20" />
                </div>
                <div className="space-y-2 max-w-xs">
                  <h4 className="text-xl font-bold text-white/40">No Investigation Active</h4>
                  <p className="text-sm text-gray-500 leading-relaxed">
                    Select a violation from the static analysis results to trigger a deep AI-powered security audit.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
      <PageToast toast={toast} onDismiss={() => setToast(null)} />
    </div>
  );
}
