name: OpenSSF Scorecard

on:
  schedule:
    - cron: "0 5 * * 1"
  push:
    branches: [main, master]

permissions: read-all

concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: false

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
